name: Build & Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: tonyodell/rakudo-nightly:latest
    steps:
      - run: apt update && apt install -y libcsv
      - run: zef test . && zef install .
