name: Build & Test
on: [push]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: tonyodell/rakudo-nightly:latest
    steps:
      - name: install deps
        run: apt update && apt install -y libcsv
      - name: tests ok
        run: zef test .
      - name: installs ok
        run: zef install .
