version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt-get update
              sudo apt-get install -y libcsv-dev build-essential
              zef install --deps-only .
      - run:
          name: test 
          command: |
              zef test .
