version: 2
jobs:
  build:

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              sudo apt-get install -y libcsv-dev
              zef build .
              zef install --deps-only .
      - run:
          name: test 
          command: |
              zef test .
